baseurl = "/"
languageCode = "pl"
title = "Schronisko w Wąworkowie"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Schronisko w Wąworkowie"
	description = "Działamy od 1996 roku. Pomagamy w trudnych sytuacjach życiowych."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Schronisko dla Kobiet i Mężczyzn**<br>w Wąworkowie pod Opatowem<br><br>**tel. 888 210 924**<br>**27-500 Opatów**<br>**Wąworków 34**"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; PT",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Działamy od 1996 roku. Pomagamy w trudnych sytuacjach życiowych."
		content = "Nasze Schronisko prowadzone jest przez Stowarzyszenie Samotnych Rencistów, Emerytów i Inwalidów w Pobroszynie.<br>Schronisko położone jest w spokojnej i malowniczej okolicy, około 5 km. od Opatowa. Teren, na którym zlokalizowane jest schronisko umożliwia prowadzenie ogrodu, jest miejsce dla zwierząt domowych a przede wszystkim daje możliwość wyciszenia poprzez codzienny kontakt z przyrodą.<br>W okolicy schroniska znajdują się szlaki turystyczne biegnące doliną Opatówki, do źródełka św. Wincentego Kadłubka czy średniowiecznej baszty w Tudorowie."


	[params.portfolio]
		hide  = false
		title = "Galeria Zdjęć"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		hide  = false
		title = "Skontaktuj się"
		content = "Zachęcamy do kontaktu telefonicznego ale możesz użyć również poniższego formularza konkaktowego"

		address = [
			"27-500 Opatów",
			"Wąworków 34"
		]
		phone = "888 210 924"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "paweltar@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Imię"
			email = "Email"
			message = "Wiadomość"
			submit = "Wyślij wiadomość"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Strona Główna"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "O nas"
	url  = "about/"
	weight = 10

[[menu.main]]
	name = "Częste pytania"
	url  = "faq/"
	weight = 15
